name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: JosephNaberhaus/actions/release-go-binary@v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check formatting
        uses: JosephNaberhaus/actions/go-check-formatting@v1.3.0

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: JosephNaberhaus/actions/go-test@v1.3.0
